/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import java.awt.CardLayout;

/**
 *
 * @author AJ
 */
public class AdminDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        cardPanel.setLayout(new java.awt.CardLayout());
        jPanel1.add(btnHome);

        AdminHomePanel home = new AdminHomePanel();
        EmployeeManagementPanel manage = new EmployeeManagementPanel();
        AdminLeavePanel leave = new AdminLeavePanel();
        BulkPayrollPanel payroll = new BulkPayrollPanel();

        cardPanel.add(home, "cardHome");
        cardPanel.add(manage, "cardEmployeeManagement");
        cardPanel.add(leave, "cardLeaveApprovals");
        cardPanel.add(payroll, "cardBulkPayroll");

        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardHome");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageEmployees = new javax.swing.JButton();
        btnApproveLeave = new javax.swing.JButton();
        btnBulkPayroll = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnManageEmployees.setText("Manage Employees");
        btnManageEmployees.addActionListener(this::btnManageEmployeesActionPerformed);

        btnApproveLeave.setText("Approve Leave");
        btnApproveLeave.addActionListener(this::btnApproveLeaveActionPerformed);

        btnBulkPayroll.setText("Bulk Payroll");
        btnBulkPayroll.addActionListener(this::btnBulkPayrollActionPerformed);

        btnHome.setText("Home");
        btnHome.addActionListener(this::btnHomeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnApproveLeave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBulkPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnManageEmployees)
                .addGap(18, 18, 18)
                .addComponent(btnApproveLeave)
                .addGap(18, 18, 18)
                .addComponent(btnBulkPayroll)
                .addGap(193, 193, 193)
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardEmployeeManagement");
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnApproveLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveLeaveActionPerformed
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardLeaveApprovals");
    }//GEN-LAST:event_btnApproveLeaveActionPerformed

    private void btnBulkPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBulkPayrollActionPerformed
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardBulkPayroll");
    }//GEN-LAST:event_btnBulkPayrollActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardHome");
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveLeave;
    private javax.swing.JButton btnBulkPayroll;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private com.motorph.ui.EmployeeManagementPanel pnlManage;
    private com.motorph.ui.AdminLeavePanel pnlLeave;
    private com.motorph.ui.BulkPayrollPanel pnlPayroll;
}
