/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.ui;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author AJ
 */
public class AdminLeavePanel extends javax.swing.JPanel {

    public AdminLeavePanel() {
        initComponents();
        loadTableData();
    }

    public final void loadTableData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader("leave_requests.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(",");
                if (data.length >= 5) {
                    String status = data[4].trim().replace("\"", "");

                    if (status.equalsIgnoreCase("PENDING")) {
                        model.addRow(data);
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error loading table: " + e.getMessage());
        }
    }

    private void processRequest(boolean approve) {
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a request first.");
            return;
        }

        String targetId = tblRequests.getValueAt(selectedRow, 0).toString().trim();
        String targetStartDate = tblRequests.getValueAt(selectedRow, 1).toString().trim();
        String newStatus = approve ? "APPROVED" : "REJECTED";

        List<String> allLines = new ArrayList<>();
        boolean found = false;

        try (BufferedReader br = new BufferedReader(new FileReader("leave_requests.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(",");
                if (data.length >= 5) {
                    String currentId = data[0].replace("\"", "").trim();
                    String currentStartDate = data[1].replace("\"", "").trim();

                    if (currentId.equals(targetId) && currentStartDate.equals(targetStartDate)) {
                        data[4] = newStatus;
                        line = String.join(",", data);
                        found = true;
                    }
                }
                allLines.add(line);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage());
            return;
        }

        if (!allLines.isEmpty()) {
            try (PrintWriter out = new PrintWriter(new FileWriter("leave_requests.csv", false))) {
                for (String line : allLines) {
                    out.println(line);
                }
                out.flush();

                JOptionPane.showMessageDialog(this, "Request " + newStatus);
                loadTableData();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error writing to file: " + e.getMessage());
            }
        }
    }

    /**
     * Creates new form AdminLeavePanel
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Start Date", "End Date", "Reason", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequests);

        btnApprove.setText("Approve");
        btnApprove.addActionListener(this::btnApproveActionPerformed);

        btnReject.setText("Reject");
        btnReject.addActionListener(this::btnRejectActionPerformed);

        btnHistory.setText("History");
        btnHistory.addActionListener(this::btnHistoryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnApprove)
                .addGap(45, 45, 45)
                .addComponent(btnReject)
                .addGap(46, 46, 46)
                .addComponent(btnHistory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject)
                    .addComponent(btnHistory))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        processRequest(true);

    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        processRequest(false);
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        LeaveHistoryDialog history = new LeaveHistoryDialog(null, true);
        history.setLocationRelativeTo(this);
        history.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
