/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.ui;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Vector;
import java.time.LocalTime;
import java.time.Duration;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author AJ
 */
public class AttendancePanel extends javax.swing.JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AttendancePanel.class.getName());

    public long loadAttendanceData(String employeeId) {
        DefaultTableModel model = (DefaultTableModel) tblAttendance.getModel();
        model.setRowCount(0);

        long totalMinutes = 0; // To keep track of the sum

        String csvFile = "MotorPH Employee Data - Attendance Record.csv";
        String line;

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            br.readLine();

            while ((line = br.readLine()) != null) {
                String[] data = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");

                if (data.length >= 6) {
                    String idInCsv = data[0].replace("\"", "").trim();

                    if (idInCsv.equals(employeeId)) {
                        String timeInStr = data[4].replace("\"", "").trim();
                        String timeOutStr = data[5].replace("\"", "").trim();

                        // 1. Calculate duration for this row
                        Duration duration = getDuration(timeInStr, timeOutStr);
                        totalMinutes += duration.toMinutes(); // Add to running total

                        // 2. Format for table display
                        long h = duration.toHours();
                        long m = duration.toMinutesPart();
                        String formattedRowTime = String.format("%d hrs %02d mins", h, m);

                        Vector<String> row = new Vector<>();
                        row.add(data[3].replace("\"", ""));
                        row.add(timeInStr);
                        row.add(timeOutStr);
                        row.add(formattedRowTime);
                        model.addRow(row);
                    }
                }
            }

            // 3. After the loop, update the Total Label
            long totalH = totalMinutes / 60;
            long totalM = totalMinutes % 60;
            lblTotalHours.setText(String.format("Total Hours Worked: %d hrs %02d mins", totalH, totalM));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        return totalMinutes;        
    }

    private String calculateHours(String timeIn, String timeOut) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("H:mm");

            LocalTime start = LocalTime.parse(timeIn, formatter);
            LocalTime end = LocalTime.parse(timeOut, formatter);

            Duration duration = Duration.between(start, end);

            long hours = duration.toHours();
            long minutes = duration.toMinutesPart();

            return String.format("%d hrs %02d mins", hours, minutes);
        } catch (Exception e) {
            return "0 hrs 00 mins";
        }
    }
    
    private Duration getDuration(String timeIn, String timeOut) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("H:mm");
            LocalTime start = LocalTime.parse(timeIn, formatter);
            LocalTime mysteries = LocalTime.parse(timeOut, formatter);
            return Duration.between(start, mysteries);
        } catch (Exception e) {
            return Duration.ZERO;
        }
    }

    /**
     * Creates new form AttendancePanel
     */
    public AttendancePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        lblTotalHours = new javax.swing.JLabel();

        tblAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time In", "Time Out", "Hours Worked"
            }
        ));
        tblAttendance.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblAttendance);

        lblTotalHours.setText("Total Hours Worked: 0 hrs 00 mins");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTotalHours)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalHours)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalHours;
    private javax.swing.JTable tblAttendance;
    // End of variables declaration//GEN-END:variables
}
