/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.ui;

import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AJ
 */
public final class BulkPayrollPanel extends javax.swing.JPanel {

    public void generateMasterPayroll() {
        DefaultTableModel model = (DefaultTableModel) tblPayroll.getModel();
        model.setRowCount(0);

        try {
            com.motorph.service.EmployeeService service = new com.motorph.service.EmployeeService();
            List<com.motorph.model.Employee> allEmployees = service.getAllEmployees();

            for (com.motorph.model.Employee emp : allEmployees) {
                double gross = emp.getBasicSalary();
                double sss = com.motorph.service.SalaryCalculator.calculateSSS(gross);
                double taxableIncome = gross - sss;
                double tax = com.motorph.service.SalaryCalculator.calculateTax(taxableIncome);
                double net = gross - sss - tax;

                model.addRow(new Object[]{
                    emp.getId(),
                    emp.getFullName(),
                    String.format("%.2f", gross),
                    String.format("%.2f", sss),
                    String.format("%.2f", tax),
                    String.format("%.2f", net)
                });
            }
        } catch (IOException e) {
            System.err.println("Error loading payroll: " + e.getMessage());
        }
    }

    /**
     * Creates new form BulkPayrollPanel
     */
    public BulkPayrollPanel() {
        initComponents();
        generateMasterPayroll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayroll = new javax.swing.JTable();

        tblPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Gross", "SSS", "Tax", "Net Pay"
            }
        ));
        jScrollPane1.setViewportView(tblPayroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayroll;
    // End of variables declaration//GEN-END:variables
}
