/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

/**
 *
 * @author AJ
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    private com.motorph.model.Employee currentUser;
    private javax.swing.JLabel lblWelcomeName;
    private javax.swing.JLabel lblIdValue;
    private javax.swing.JLabel lblPositionValue;
    private javax.swing.JLabel lblRateValue;
    private AttendancePanel pnlAttendance;
    private SalaryPanel pnlSalary;

    public EmployeeDashboard(com.motorph.model.Employee user) {
        this.currentUser = user;
        initComponents();

        ProfilePanel pnlProfile = new ProfilePanel();
        pnlAttendance = new AttendancePanel();
        LeaveRequestPanel pnlLeave = new LeaveRequestPanel(currentUser);
        pnlSalary = new SalaryPanel(currentUser);

        cardPanel.setLayout(new java.awt.CardLayout());
        cardPanel.add(pnlProfile, "cardProfile");
        cardPanel.add(pnlAttendance, "cardAttendance");
        cardPanel.add(pnlLeave, "cardLeave");
        cardPanel.add(pnlSalary, "cardSalary");

        pnlProfile.setEmployeeData(user);

        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardProfile");

        this.pack();
        this.setLocationRelativeTo(null);
    }

    private void displayEmployeeData() {
        try {
            if (currentUser != null) {
                if (lblWelcomeName != null) {
                    lblWelcomeName.setText("Welcome, " + currentUser.getFullName());
                }
                if (lblIdValue != null) {
                    lblIdValue.setText(currentUser.getId());
                }
                if (lblPositionValue != null) {
                    lblPositionValue.setText(currentUser.getPosition());
                }
                if (lblRateValue != null) {
                    lblRateValue.setText(String.valueOf(currentUser.getHourlyRate()));
                }
            }
        } catch (Exception e) {
            System.err.println("Error displaying data: " + e.getMessage());
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName());

    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProfile = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnLeaveRequest = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 51, 255));

        btnProfile.setText("My Profile");
        btnProfile.addActionListener(this::btnProfileActionPerformed);

        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(this::btnAttendanceActionPerformed);

        btnLeaveRequest.setText("Leave Request");
        btnLeaveRequest.addActionListener(this::btnLeaveRequestActionPerformed);

        btnSalary.setText("Salary");
        btnSalary.addActionListener(this::btnSalaryActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeaveRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnProfile)
                .addGap(18, 18, 18)
                .addComponent(btnAttendance)
                .addGap(18, 18, 18)
                .addComponent(btnLeaveRequest)
                .addGap(18, 18, 18)
                .addComponent(btnSalary)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardAttendance");

        pnlAttendance.loadAttendanceData(currentUser.getId());
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardProfile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLeaveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveRequestActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardLeave");
    }//GEN-LAST:event_btnLeaveRequestActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        long totalMinutes = pnlAttendance.loadAttendanceData(currentUser.getId());

        double hoursWorked = totalMinutes / 60.0;

        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "cardSalary");

        //pnlSalary.setHoursAndCalculate(hoursWorked);
    }//GEN-LAST:event_btnSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnLeaveRequest;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSalary;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
