/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.ui;

/**
 *
 * @author AJ
 */
public class LeaveRequestPanel extends javax.swing.JPanel {

    private com.motorph.model.Employee currentUser;

    /**
     * Creates new form LeaveRequestPanel
     */
    public LeaveRequestPanel(com.motorph.model.Employee user) {
        this.currentUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        txtStartEnd = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        btnSubmitLeave = new javax.swing.JButton();
        cmbReason = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("Leave Request");

        lblStartDate.setText("Start Date:");

        lblEndDate.setText("End Date:");

        btnSubmitLeave.setText("Submit");
        btnSubmitLeave.addActionListener(this::btnSubmitLeaveActionPerformed);

        cmbReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation", "Sick", "Holiday" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStartDate)
                                    .addComponent(lblEndDate))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbReason, 0, 258, Short.MAX_VALUE)
                                    .addComponent(txtStartEnd)
                                    .addComponent(txtEndDate)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnSubmitLeave)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(cmbReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDate)
                    .addComponent(txtStartEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSubmitLeave)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitLeaveActionPerformed
        String startDate = txtStartEnd.getText().trim();
        String endDate = txtEndDate.getText().trim();
        String reason = cmbReason.getSelectedItem().toString();
        String employeeId = currentUser.getId();
        String status = "PENDING";

        if (startDate.isEmpty() || endDate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all date fields.");
            return;
        }

        try (java.io.FileWriter fw = new java.io.FileWriter("leave_requests.csv", true); java.io.BufferedWriter bw = new java.io.BufferedWriter(fw); java.io.PrintWriter out = new java.io.PrintWriter(bw)) {

            out.println(employeeId + "," + startDate + "," + endDate + "," + reason + "," + status);

            javax.swing.JOptionPane.showMessageDialog(this, "Leave request submitted successfully!");

            txtStartEnd.setText("");
            txtEndDate.setText("");

        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving request: " + e.getMessage());
        }
        btnSubmitLeave.addActionListener(this::btnSubmitLeaveActionPerformed);
    }//GEN-LAST:event_btnSubmitLeaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitLeave;
    private javax.swing.JComboBox<String> cmbReason;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartEnd;
    // End of variables declaration//GEN-END:variables
}
