/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;
import com.motorph.model.Employee;

/**
 *
 * @author AJ
 */
public class ProfilePanel extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfilePanel.class.getName());
    
    public void setEmployeeData(Employee emp) {
    lblID.setText("Employee ID: " + emp.getId());
    lblName.setText("Name: " + emp.getFullName());
    lblPosition.setText("Position: " + emp.getPosition());
    lblBirthday.setText("Birthday: " + emp.getBirthday());
    lblHourlyRate.setText("Hourly Rate: PHP " + emp.getHourlyRate());
    lblSSS.setText("SSS #: " + emp.getSss());
    lblTIN.setText("TIN #: " + emp.getTin());
    lblPhilhealth.setText("Philhealth #: " + emp.getPhilhealth());
    lblPagibig.setText("Pag-ibig #: " + emp.getPagibig());
    lblAddress.setText("Address: " + emp.getAddress());
    lblPhone.setText("Phone #:" + emp.getPhone());
    }
    
    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblHourlyRate = new javax.swing.JLabel();
        lblSSS = new javax.swing.JLabel();
        lblTIN = new javax.swing.JLabel();
        lblPhilhealth = new javax.swing.JLabel();
        lblPagibig = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();

        lblID.setText("ID:");

        lblName.setText("Name:");

        lblPosition.setText("Position:");

        lblHourlyRate.setText("Salary:");

        lblSSS.setText("SSS:");

        lblTIN.setText("TIN #:");

        lblPhilhealth.setText("PhilHealth #:");

        lblPagibig.setText("Pag-ibig #:");

        lblAddress.setText("Address:");

        lblPhone.setText("Phone #:");

        lblBirthday.setText("Birthday:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhone)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHourlyRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhilhealth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPagibig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lblID)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblBirthday)
                .addGap(18, 18, 18)
                .addComponent(lblAddress)
                .addGap(18, 18, 18)
                .addComponent(lblPosition)
                .addGap(18, 18, 18)
                .addComponent(lblPhone)
                .addGap(18, 18, 18)
                .addComponent(lblHourlyRate)
                .addGap(18, 18, 18)
                .addComponent(lblSSS)
                .addGap(18, 18, 18)
                .addComponent(lblTIN)
                .addGap(18, 18, 18)
                .addComponent(lblPhilhealth)
                .addGap(18, 18, 18)
                .addComponent(lblPagibig)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPagibig;
    private javax.swing.JLabel lblPhilhealth;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSSS;
    private javax.swing.JLabel lblTIN;
    // End of variables declaration//GEN-END:variables
}