/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.Employee;
import com.motorph.service.SalaryService;
import javax.swing.JOptionPane;

/**
 *
 * @author AJ
 */
public class SalaryPanel extends javax.swing.JPanel {

    private com.motorph.model.Employee currentUser;

    public void performCalculations(double hours) {
        try {
            double rate = currentUser.getHourlyRate();
            double gross = rate * hours;

            double sss = com.motorph.service.SalaryCalculator.calculateSSS(gross);
            double ph = com.motorph.service.SalaryCalculator.calculatePhilHealth(gross);
            double pi = com.motorph.service.SalaryCalculator.calculatePagIBIG(gross);

            double taxableIncome = gross - (sss + ph + pi);
            double tax = com.motorph.service.SalaryCalculator.calculateTax(taxableIncome);
            double net = gross - (sss + ph + pi + tax);

            lblGrossPay.setText(String.format("Gross: PHP %,.2f", gross));
            lblSSS.setText(String.format("SSS: PHP %,.2f", sss));
            lblPhilHealth.setText(String.format("PhilHealth: PHP %,.2f", ph));
            lblPagibig.setText(String.format("Pag-ibig: PHP %,.2f", pi));
            lblTax.setText(String.format("Tax: PHP %,.2f", tax));
            lblNetPay.setText(String.format("Net Pay: PHP %,.2f", net));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error calculating salary: " + e.getMessage());
        }
    }

    public SalaryPanel(Employee currentUser) {
        this.currentUser = currentUser;
        initComponents();

        if (this.currentUser != null) {
            double rate = this.currentUser.getHourlyRate();
            lblRateDisplay.setText("Your Hourly Rate: PHP " + String.format("%.2f", rate));
        }
    }

    /**
     * Creates new form SalaryPanel
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHoursWorked = new javax.swing.JLabel();
        txtHoursWorked = new javax.swing.JTextField();
        lblPayroll = new javax.swing.JLabel();
        lblGrossPay = new javax.swing.JLabel();
        lblSSS = new javax.swing.JLabel();
        lblPhilHealth = new javax.swing.JLabel();
        lblPagibig = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblNetPay = new javax.swing.JLabel();
        lblRateDisplay = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTotalDeductions = new javax.swing.JLabel();

        lblHoursWorked.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoursWorked.setText("Hours Worked:");

        lblPayroll.setText("Payroll");

        lblGrossPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrossPay.setText("Gross Pay:");

        lblSSS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSSS.setText("SSS:");

        lblPhilHealth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhilHealth.setText("PhilHealth:");

        lblPagibig.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPagibig.setText("Pag-ibig:");

        lblTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTax.setText("Tax:");

        lblNetPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNetPay.setText("Net Pay:");

        lblRateDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRateDisplay.setText("Rate:");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        lblTotalDeductions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalDeductions.setText("Total Deductions:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(btnCalculate)
                            .addGap(122, 122, 122))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblGrossPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSSS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhilHealth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPagibig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNetPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalDeductions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHoursWorked, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(lblRateDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(btnClear))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblPayroll)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPayroll)
                .addGap(18, 18, 18)
                .addComponent(lblRateDisplay)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoursWorked)
                    .addComponent(txtHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGrossPay)
                .addGap(18, 18, 18)
                .addComponent(lblSSS)
                .addGap(18, 18, 18)
                .addComponent(lblPhilHealth)
                .addGap(18, 18, 18)
                .addComponent(lblPagibig)
                .addGap(18, 18, 18)
                .addComponent(lblTax)
                .addGap(18, 18, 18)
                .addComponent(lblNetPay)
                .addGap(18, 18, 18)
                .addComponent(lblTotalDeductions)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnClear))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try {
            String input = txtHoursWorked.getText().trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter hours worked.");
                return;
            }

            double hours = Double.parseDouble(input);
            updateAllPayrollLabels(hours);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a numeric value for hours.");
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void updateAllPayrollLabels(double hours) {
        SalaryService salaryService = new SalaryService();

        double netPay = salaryService.calculateWeeklyNet(currentUser, hours);
        double rate = currentUser.getHourlyRate();
        double grossPay = rate * hours;

        double sss = salaryService.calculateSSS(currentUser.getBasicSalary()) / 4;
        double ph = salaryService.calculatePhilhealth(currentUser.getBasicSalary()) / 4;
        double pi = 100.00 / 4;

        double taxableIncome = grossPay - (sss + ph + pi);
        double tax = salaryService.calculateWithholdingTax(taxableIncome);
        double totalDeductions = sss + ph + pi + tax;

        lblGrossPay.setText(String.format("Gross Pay: PHP %,.2f", grossPay));
        lblSSS.setText(String.format("SSS: PHP %,.2f", sss));
        lblPhilHealth.setText(String.format("PhilHealth: PHP %,.2f", ph));
        lblPagibig.setText(String.format("Pag-ibig: PHP %,.2f", pi));
        lblTax.setText(String.format("Tax: PHP %,.2f", tax));
        lblTotalDeductions.setText(String.format("Total Deductions: PHP %,.2f", totalDeductions));
        lblNetPay.setText(String.format("Net Pay: PHP %,.2f", netPay));

        this.revalidate();
        this.repaint();
    }

    public void setHoursAndCalculate(double hours) {
        if (txtHoursWorked != null) {
            if (txtHoursWorked.getText().isEmpty()) {
                txtHoursWorked.setText(String.format("%.2f", hours));
                updateAllPayrollLabels(hours);
            }
        }
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtHoursWorked.setText("");
        lblGrossPay.setText("0.00");
        lblTotalDeductions.setText("0.00");
        lblNetPay.setText("0.00");

        txtHoursWorked.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel lblGrossPay;
    private javax.swing.JLabel lblHoursWorked;
    private javax.swing.JLabel lblNetPay;
    private javax.swing.JLabel lblPagibig;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblPhilHealth;
    private javax.swing.JLabel lblRateDisplay;
    private javax.swing.JLabel lblSSS;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotalDeductions;
    private javax.swing.JTextField txtHoursWorked;
    // End of variables declaration//GEN-END:variables
}
